const categories=[['vase','🏺','花器'],['decor','✨','裝飾用品'],['ceremony','🎎','法會用品'],['clothes','👘','服飾'],['equipment','🔧','器材'],['other','📦','其他']];
const colors=['#8da99c','#b49c81','#8795aa','#b18ea8','#9b8f83','#7e9cac'];
function art(label,icon,color){return `<svg viewBox="0 0 480 360" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="${label} 測試圖片"><defs><linearGradient id="g" x1="0" x2="1" y1="0" y2="1"><stop stop-color="${color}"/><stop offset="1" stop-color="#eef1ef"/></linearGradient></defs><rect width="480" height="360" fill="url(#g)"/><circle cx="390" cy="75" r="70" fill="rgba(255,255,255,.25)"/><text x="240" y="185" text-anchor="middle" font-size="92">${icon}</text><text x="240" y="270" text-anchor="middle" font-size="28" font-family="Arial,sans-serif" fill="#20332b">測試照片</text></svg>`}
const assets=[
{id:'M001',cat:'vase',name:'白色方形花器',qty:18,place:'測試區 A1＋B2',icon:'⬜',color:colors[0],detail:'同一資材可分散在兩個儲位；詳細頁會列出各位置數量。',stock:['測試區 A1：6 個','測試區 B2：12 個']},
{id:'M002',cat:'vase',name:'綠色玻璃花器',qty:6,place:'測試區 C3',icon:'🏺',color:colors[1],detail:'照片牆卡片顯示名稱、可用數量與位置。'},
{id:'M003',cat:'vase',name:'高型花器',qty:4,place:'測試區 A4',icon:'🏺',color:colors[2],detail:'群組照片、多照片等資料模型留到正式資料層處理。'},
{id:'M004',cat:'decor',name:'三層展示架',qty:2,place:'測試區 D1',icon:'✨',color:colors[3],detail:'數量管理示例。'},
{id:'M005',cat:'decor',name:'布料收納箱',qty:1,place:'測試區 E2',icon:'🧵',color:colors[4],detail:'套組／整箱管理示例。',badge:'管理方式待確認'},
{id:'M006',cat:'ceremony',name:'儀式標示牌',qty:3,place:'測試區 F1',icon:'🪧',color:colors[5],detail:'法會用品測試資料。'},
{id:'M007',cat:'ceremony',name:'粉色胸花',qty:29,place:'測試區 F2',icon:'🌸',color:colors[3],detail:'數量管理示例。'},
{id:'M008',cat:'clothes',name:'服飾收納箱',qty:1,place:'測試區 G1',icon:'👘',color:colors[1],detail:'套組／整箱管理示例。'},
{id:'M009',cat:'equipment',name:'無線通訊器',qty:12,place:'測試區 H1',icon:'📻',color:colors[2],detail:'單件追蹤示例。'},
{id:'M010',cat:'equipment',name:'通訊器耳機',qty:14,place:'測試區 H1',icon:'🎧',color:colors[0],detail:'配件可採數量管理。'},
{id:'M011',cat:'other',name:'收納工具箱',qty:2,place:'測試區 I1',icon:'🧰',color:colors[4],detail:'其他類別測試資料。'}];
let cart=JSON.parse(localStorage.getItem('assetTestCart')||'{}');let lastSearch=[];let deferredInstallPrompt=null;
function saveCart(){localStorage.setItem('assetTestCart',JSON.stringify(cart));updateCartBar()}
function renderCats(){document.getElementById('catGrid').innerHTML=categories.map(([id,icon,name])=>`<button class="cat-btn" onclick="goCategory('${id}')"><span class="icon">${icon}</span><b>${name}</b><small>直接看照片</small></button>`).join('')}
function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById(id).classList.add('active');window.scrollTo(0,0);updateCartBar()}
function setHash(h){if(location.hash===h){route()}else location.hash=h}
function goHome(){setHash('#home')}function goCategory(id){setHash('#category/'+id)}function goCart(){setHash('#cart')}function goMyBorrow(){setHash('#myborrow')}function goAdmin(){setHash('#admin')}function goAddAsset(){setHash('#addasset')}
function route(){const h=location.hash||'#home';if(h.startsWith('#category/')){renderCategory(h.split('/')[1]);showView('category')}else if(h==='#search'){renderSearch();showView('category')}else if(h==='#cart'){renderCart();showView('cart')}else if(h==='#myborrow'){renderBorrowList();showView('myborrow')}else if(h==='#admin'){showView('admin')}else if(h==='#addasset'){showView('addasset')}else{showView('home')}}
function renderCategory(cat){const meta=categories.find(c=>c[0]===cat);document.getElementById('categoryTitle').textContent=`${meta?.[1]||'📦'} ${meta?.[2]||'資材'}`;document.getElementById('categorySubtitle').textContent='只顯示這一大類；往下不會接到其他類別。';const list=assets.filter(a=>a.cat===cat);renderAssetGrid(list)}
function renderSearch(){document.getElementById('categoryTitle').textContent='🔎 搜尋結果';document.getElementById('categorySubtitle').textContent='搜尋只是備用入口；仍然以照片挑選為主。';renderAssetGrid(lastSearch)}
function renderAssetGrid(list){document.getElementById('assetGrid').innerHTML=list.length?list.map(assetCard).join(''):'<div class="empty">沒有符合的測試資材。</div>'}
function assetCard(a){const count=cart[a.id]||0;return `<article class="asset"><button style="border:0;padding:0;width:100%;background:transparent" onclick="openDetail('${a.id}')"><div class="asset-media">${art(a.name,a.icon,a.color)}</div></button><div class="asset-body"><div class="asset-name">${a.name}</div><div class="asset-meta">可用 ${a.qty}｜${a.place}</div>${a.badge?`<span class="badge">${a.badge}</span>`:''}<div class="asset-actions"><button class="btn secondary wide" onclick="openDetail('${a.id}')">查看詳細</button><div class="qty-row"><input id="card-qty-${a.id}" type="number" min="1" max="${a.qty}" value="${count||1}" aria-label="數量"><button class="btn primary" style="flex:1" onclick="addCartFromInput('${a.id}','card-qty-${a.id}')">加入清單</button></div></div></div></article>`}
function addCartFromInput(id,inputId){const a=assets.find(x=>x.id===id);const el=document.getElementById(inputId);let n=Math.max(1,Math.min(a.qty,Number(el?.value)||1));cart[id]=n;saveCart();toast(`已加入：${a.name} × ${n}`)}
function updateCartBar(){const entries=Object.entries(cart).filter(([,q])=>q>0);const bar=document.getElementById('stickyCart');const total=entries.reduce((s,[,q])=>s+q,0);document.getElementById('cartCount').textContent=`${entries.length} 項／${total} 件`;bar.classList.toggle('show',entries.length>0&&!document.getElementById('cart').classList.contains('active'))}
function openDetail(id){const a=assets.find(x=>x.id===id);document.getElementById('detailName').textContent=a.name;document.getElementById('detailMeta').textContent=`可用 ${a.qty}｜${a.place}`;document.getElementById('detailPhoto').innerHTML=art(a.name,a.icon,a.color);document.getElementById('detailBody').innerHTML=`<p style="line-height:1.65">${a.detail}</p>${a.stock?`<div class="list-card"><b>各儲位</b><div class="muted" style="margin-top:7px;line-height:1.7">${a.stock.join('<br>')}</div></div>`:''}<div class="qty-row" style="margin-top:12px"><input id="modal-qty-${a.id}" type="number" min="1" max="${a.qty}" value="${cart[a.id]||1}"><button class="btn primary" style="flex:1" onclick="addCartFromInput('${a.id}','modal-qty-${a.id}');closeDetail()">加入使用清單</button></div>`;document.getElementById('detailModal').classList.add('open')}
function closeDetail(){document.getElementById('detailModal').classList.remove('open')}
function renderCart(){const entries=Object.entries(cart).filter(([,q])=>q>0);document.getElementById('cartList').innerHTML=entries.length?entries.map(([id,q])=>{const a=assets.find(x=>x.id===id);return `<div class="list-card"><div class="row"><div><b>${a.name}</b><div class="muted" style="margin-top:4px">${a.place}</div></div><button class="btn danger" onclick="removeCart('${id}')">移除</button></div><div class="qty-row" style="margin-top:10px"><span class="muted">數量</span><input type="number" min="1" max="${a.qty}" value="${q}" onchange="changeCart('${id}',this.value)"></div></div>`}).join(''):'<div class="empty">使用清單目前是空的。回照片牆加入幾項試試看。</div>';const today=new Date();const plus=new Date(today);plus.setDate(plus.getDate()+3);document.getElementById('useDate').value ||= fmt(today);document.getElementById('returnDate').value ||= fmt(plus)}
function fmt(d){const y=d.getFullYear();const m=String(d.getMonth()+1).padStart(2,'0');const day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}function removeCart(id){delete cart[id];saveCart();renderCart()}function changeCart(id,v){const a=assets.find(x=>x.id===id);cart[id]=Math.max(1,Math.min(a.qty,Number(v)||1));saveCart()}
function submitBorrow(){const entries=Object.entries(cart).filter(([,q])=>q>0);if(!entries.length){toast('請先加入資材');return}if(!document.getElementById('purpose').value.trim()){toast('請填法會／用途');document.getElementById('purpose').focus();return}localStorage.setItem('assetTestLastBorrow',JSON.stringify({items:entries,purpose:document.getElementById('purpose').value,useDate:document.getElementById('useDate').value,returnDate:document.getElementById('returnDate').value}));cart={};saveCart();toast('測試借用單已建立（只存在本機）');goMyBorrow()}
function renderBorrowList(){const local=JSON.parse(localStorage.getItem('assetTestLastBorrow')||'null');const cards=[];cards.push(`<div class="list-card"><div class="row"><div><b>測試法會｜使用中</b><div class="muted" style="margin-top:4px">預計歸還：2026-09-12</div></div><span class="badge">使用中</span></div><div class="divider"></div><div class="muted">白色方形花器 × 6<br>粉色胸花 × 4</div><button class="btn secondary wide" style="margin-top:12px" onclick="openReturn()">我要歸還</button></div>`);if(local){cards.unshift(`<div class="list-card"><div class="row"><div><b>${escapeHtml(local.purpose)}｜測試新增</b><div class="muted" style="margin-top:4px">${local.useDate||'未填'} → ${local.returnDate||'未填'}</div></div><span class="badge">本機測試</span></div><div class="divider"></div><div class="muted">${local.items.map(([id,q])=>`${assets.find(a=>a.id===id)?.name||id} × ${q}`).join('<br>')}</div><button class="btn secondary wide" style="margin-top:12px" onclick="openReturn()">我要歸還</button></div>`)}document.getElementById('borrowList').innerHTML=cards.join('')}
function openReturn(){document.getElementById('returnModal').classList.add('open')}function closeReturn(){document.getElementById('returnModal').classList.remove('open')}function finishReturn(status){closeReturn();toast(status==='全部正常'?'測試歸還完成':'已建立「待處理」測試狀態')}
function searchAssets(){const q=document.getElementById('searchInput').value.trim().toLowerCase();if(!q){toast('請輸入名稱');return}lastSearch=assets.filter(a=>(a.name+' '+a.place).toLowerCase().includes(q));setHash('#search')}
function previewPhoto(e){const f=e.target.files?.[0];if(!f)return;const url=URL.createObjectURL(f);document.getElementById('previewImg').src=url;document.getElementById('preview').classList.add('show')}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),1800)}function escapeHtml(s){return String(s).replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
function platform(){const ua=navigator.userAgent||'';if(/iPhone|iPad|iPod/i.test(ua))return'ios';if(/Android/i.test(ua))return'android';return'desktop'}
function setupInstallCard(){if(localStorage.getItem('assetInstallHintDismissed')==='1'){document.getElementById('installCard').style.display='none';return}const p=platform();const title=document.getElementById('installTitle');const text=document.getElementById('installText');if(p==='ios'){title.textContent='iPhone／iPad：網址直接開就能用';text.textContent='常用時可從 Safari「分享 → 加入主畫面」固定成圖示。'}else if(p==='android'){title.textContent='Android：網址直接開就能用';text.textContent='Chrome 支援時可直接安裝成網頁 App；不安裝也完全能用。'}else{title.textContent='桌機：瀏覽器直接開就能用';text.textContent='Chrome／Edge 支援時可安裝成獨立網頁 App；也可只存書籤。'}}
function dismissInstall(){localStorage.setItem('assetInstallHintDismissed','1');document.getElementById('installCard').style.display='none'}
async function installApp(){if(deferredInstallPrompt){deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;return}const p=platform();const help=document.getElementById('installHelp');if(p==='ios')help.innerHTML='1. 請用 Safari 開啟這個網址。<br>2. 點下方「分享」圖示。<br>3. 選「加入主畫面」，依畫面完成即可。<br><br>不加入也沒關係，網址照樣可直接使用。';else if(p==='android')help.innerHTML='請用 Chrome 開啟。若瀏覽器顯示「安裝應用程式／加到主畫面」，點下去即可；若沒有出現，直接用網址也完全正常。';else help.innerHTML='Chrome／Edge 若在網址列或選單顯示「安裝應用程式」，可直接安裝；沒有也沒關係，存書籤即可。';document.getElementById('installModal').classList.add('open')}
function closeInstallHelp(){document.getElementById('installModal').classList.remove('open')}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e});
window.addEventListener('appinstalled',()=>{document.getElementById('installCard').style.display='none';toast('已固定到裝置')});
window.addEventListener('hashchange',route);renderCats();route();updateCartBar();setupInstallCard();
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}))}